files: '^(python_cdp|scripts|tests)'
repos:
  - repo: meta
    hooks:
      - id: identity
        types: [python]
  - repo: https://github.com/ambv/black
    rev: 02f81c6995db4688baedd3c63e4b9821c090f09c
    hooks:
      - id: black
        args: [--safe, --quiet, --line-length=120]
        language_version: python3.9
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 84e478bc42d27f9c214de50dd331ca7602beb2f1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-builtin-literals
      - id: check-json
      - id: check-merge-conflict
      - id: forbid-submodules
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 32119baf69e913a72f2e1b1fbe0d56921b670ebb
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        args: [--non-interactive, --install-types]
  - repo: https://github.com/PyCQA/flake8
    rev: 4b011224b290db13178c8059034159fc333d6a6e
    hooks:
      - id: flake8
        args: [--max-line-length=120]
  - repo: https://github.com/symonk/pre-commit-pdb-vars
    rev: ae4a3643086810d62c6815527547c9dbd1f9b584
    hooks:
      - id: pdb-vars
        args: [--ignore, commands]
  - repo: https://github.com/hadialqattan/pycln
    rev: 2b2ee5d94542913e26c9e3bb38ee4d05a9e01066
    hooks:
      - id: pycln
        args: [--config=pyproject.toml, --all]
  - repo: https://github.com/PyCQA/docformatter
    rev: f1b0fa688af908cfe9d8e56420660dc1cd2daf7e
    hooks:
      - id: docformatter
        args: [-i, --wrap-summaries, "120", --wrap-descriptions, "120"]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: b72c1a5b79513ba44b56f2c65611151c0f7a950a
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]