PREAMBLE = """# Auto generated file.
# This file was automatically generated by https://github.com/symonk/pycdp
# inline with the cdp specification for version {version}.
#
# Please update the generator code to make changes here.
"""

CONSTANT_IMPORTS = """
# Domain: {domain}
from __future__ import annotations
from dataclasses import dataclass
import enum
import typing
"""


BASIC_DATACLASS = '''
@dataclass
class {clazz}:
    """{docstring}"""
'''
