""" *** AUTO GENERATED FILE ***
This file was automatically generated by python-cdp.  Do not modify this file
as it is overwritten when new versions of the devtools protocol are released.  Instead modify the
code generator in https://github.com/symonk/python-cdp (or your fork) instead.  For documentation
on how to modify the generation process refer to the CONTRIBUTING.md file in the root of the
repository."""
from __future__ import annotations
from dataclasses import dataclass


@dataclass
class BackendNode:
    """Backend node with a friendly name."""


@dataclass
class Node:
    """DOM interaction is implemented in terms of mirror objects that represent
    the actual DOM nodes.

    DOMNode is a base node mirror type.
    """


@dataclass
class RGBA:
    """A structure holding an RGBA color."""


@dataclass
class BoxModel:
    """Box model."""


@dataclass
class ShapeOutsideInfo:
    """CSS Shape Outside details."""


@dataclass
class Rect:
    """Rectangle."""


@dataclass
class CSSComputedStyleProperty:
    """Missing description in devtools protocol."""
