# Auto generated file.
# This file was automatically generated by https://github.com/symonk/python-cdp
# inline with the cdp specification for version {version}.
#
# Please update the generator code to make changes here.


# Domain: {domain}
from __future__ import annotations
from dataclasses import dataclass


@dataclass
class DevtoolsDomain:
    """Encapsulation of the CDP `DevtoolsDomain` Domain.

    This domains experimental status is: FALSE
    """
