""" *** AUTO GENERATED FILE ***
This file was automatically generated by python-cdp.  Do not modify this file
as it is overwritten when new versions of the devtools protocol are released.  Instead modify the
code generator in https://github.com/symonk/python-cdp (or your fork) instead.  For documentation
on how to modify the generation process refer to the CONTRIBUTING.md file in the root of the
repository."""
from __future__ import annotations
from dataclasses import dataclass


@dataclass
class ScreenOrientation:
    """Screen orientation."""


@dataclass
class DisplayFeature:
    """Missing description in devtools protocol."""


@dataclass
class MediaFeature:
    """Missing description in devtools protocol."""


@dataclass
class UserAgentBrandVersion:
    """Used to specify User Agent Cient Hints to emulate."""


@dataclass
class UserAgentMetadata:
    """Used to specify User Agent Cient Hints to emulate.

    will be filled in by the target with what it would normally use.
    """
