""" *** AUTO GENERATED FILE ***
This file was automatically generated by python-cdp.  Do not modify this file
as it is overwritten when new versions of the devtools protocol are released.  Instead modify the
code generator in https://github.com/symonk/python-cdp (or your fork) instead.  For documentation
on how to modify the generation process refer to the CONTRIBUTING.md file in the root of the
repository."""
from __future__ import annotations
from dataclasses import dataclass


@dataclass
class LargestContentfulPaint:
    """See https://github.com/WICG/LargestContentfulPaint and
    largest_contentful_paint.idl."""


@dataclass
class LayoutShiftAttribution:
    """Missing description in devtools protocol."""


@dataclass
class LayoutShift:
    """See https://wicg.github.io/layout-instability/#sec-layout-shift and
    layout_shift.idl."""


@dataclass
class TimelineEvent:
    """Missing description in devtools protocol."""
