""" *** AUTO GENERATED FILE ***
This file was automatically generated by python-cdp.  Do not modify this file
as it is overwritten when new versions of the devtools protocol are released.  Instead modify the
code generator in https://github.com/symonk/python-cdp (or your fork) instead.  For documentation
on how to modify the generation process refer to the CONTRIBUTING.md file in the root of the
repository."""
from __future__ import annotations
from dataclasses import dataclass


@dataclass
class ContextRealtimeData:
    """Fields in AudioContext that change in real-time."""


@dataclass
class BaseAudioContext:
    """Protocol object for BaseAudioContext."""


@dataclass
class AudioListener:
    """Protocol object for AudioListener."""


@dataclass
class AudioNode:
    """Protocol object for AudioNode."""


@dataclass
class AudioParam:
    """Protocol object for AudioParam."""
