name: python-cdp testing
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        name: [
          "ubuntu-py39",
          "ubuntu-py310",
          "ubuntu-py311",
        ]
        include:
          - name: "ubuntu-py39"
            python: "3.9"
            os: ubuntu-20.04
            tox_env: "py39"
            do_cov: false
          - name: "ubuntu-py310"
            python: "3.10"
            os: ubuntu-20.04
            tox_env: "py310"
            do_cov: true
          - name: "ubuntu-py311"
            python: "3.11"
            os: ubuntu-20.04
            tox_env: "py311"
            do_cov: false
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: 'Set up Python ${{ matrix.python }}'
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
          python -m pip install poetry
          pip --version
          tox --version
          poetry --version
      - name: Test without coverage
        if: "! matrix.do_cov"
        run: |
          tox -e ${{ matrix.tox_env }}
      - name: Test with coverage
        if: "matrix.do_cov"
        run: |
          tox -e ${{ matrix.tox_env }}
      - name: Generate cov report
        if: "matrix.do_cov"
        run: |
          tox -e report_cov
      - name: Upload to CodeCov
        if: "matrix.do_cov"
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: python_cdp_unit_tests
          fail_ci_if_error: true
          verbose: true